server:
  port: 8080

spring:
  application:
    name: scalardb-system-api-community

# ScalarDB Configuration
scalardb:
  storage:
    contact_points: localhost
    contact_port: 9042
    storage: cassandra
    username: 
    password: 

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    com.example.scalardb: DEBUG
    com.scalar.db: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/system-api.log