server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Inventory Service Logs
  - job_name: inventory-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: inventory-service
          service: inventory
          __path__: /var/log/inventory-service/*.log

  # Payment Service Logs
  - job_name: payment-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: payment-service
          service: payment
          __path__: /var/log/payment-service/*.log

  # Shipping Service Logs
  - job_name: shipping-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: shipping-service
          service: shipping
          __path__: /var/log/shipping-service/*.log

  # Order Service Logs
  - job_name: order-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: order-service
          service: order
          __path__: /var/log/order-service/*.log

  # System Logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log

  # Docker Container Logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'

pipeline_stages:
  # Parse JSON logs
  - json:
      expressions:
        timestamp: timestamp
        level: level
        message: message
        service: service
        trace_id: traceId
        span_id: spanId

  # Extract timestamp
  - timestamp:
      source: timestamp
      format: '2006-01-02T15:04:05.000Z'

  # Parse log levels
  - regex:
      expression: '(?P<level>ERROR|WARN|INFO|DEBUG|TRACE)'
      source: level

  # Label extraction
  - labels:
      level:
      service:
      trace_id:
      span_id:

  # Output formatting
  - output:
      source: message